name: Test Claude Code Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml
    
    - name: Check script permissions
      run: |
        test -x cc
        test -x scripts/cc-utils.sh
        test -x automation/auto-commit.sh
        test -x python-utils/cc_tools.py
    
    - name: Test cc launcher
      run: |
        ./cc 2>&1 | grep -q "Claude Code Tools"
    
    - name: Test Python tools
      run: |
        python3 python-utils/cc_tools.py --help
    
    - name: Shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        shellcheck cc || true
        shellcheck scripts/*.sh || true
        shellcheck automation/*.sh || true
    
    - name: Python syntax check
      run: |
        python -m py_compile python-utils/cc_tools.py